name: Healthcheck

on:
  schedule:
    - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  check-api-job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Date
        id: date-check
        run: bash .github/scripts/check-date.sh

      - name: Set up Node.js
        if: steps.date-check.outputs.skip != 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Run Check Script
        if: steps.date-check.outputs.skip != 'true'
        run: node healthcheck.js